Added custom event to fix email confirmation system
nucleos/NucleosProfileBundle pull request #156
Opened 2021-01-07 22:46 UTC by fkrauthan

Closes #153

## Subject

- Added new event class `UserFormEvent`
- Switched the `REGISTRATION_SUCCESS` event to `UserFormEvent`
- Updated `EmailConfirmationListener` to use new event type to make it work

2021-01-08 21:07 UTC, core23 requested changes

2021-01-08 21:07 UTC, core23 commented on src/Event/UserFormEvent.php
> +class UserFormEvent extends Event
Can you please extend the `Nucleos\UserBundle\Event\FormEvent` otherwise this is a BC break for someone that listens on the `REGISTRATION_SUCCESS` event.

2021-01-08 21:27 UTC, fkrauthan commented on src/Event/UserFormEvent.php
> +class UserFormEvent extends Event
Unfortunately you can't as `FormEvent` is a final class in the UserBundle (it was my initial thought to begin with). If you remove that I am happy to update this PR.

Btw this event in general is not compatible with the relevant FOSUserBundle event (might be worth pointing out). As the FOSUserBundle has as FormData the `UserInterface` instance and not a separate registration form entity.

2021-01-12 13:32 UTC, core23 commented on src/Event/UserFormEvent.php
> +class UserFormEvent extends Event
> Unfortunately you can't as `FormEvent` is a final class in the UserBundle (it was my initial thought to begin with). If you remove that I am happy to update this PR.

This is the only way to stay BC. Feel free to open a PR in the `UserBundle`.

> Btw this event in general is not compatible with the relevant FOSUserBundle event (might be worth pointing out).

This might be right. My initial idea was to alias all FOS classes. There was a [POC](https://github.com/nucleos/FOSUserBundlePolyfill), but I'm not sure if this ever worked. The time consumption for this project was too much for me so I archived this.

The current project has some 100% copy & paste parts from the FOS community but there are also some major changes, e.g. splitting the project in the user and profile bundle. This is intended, because the active development stopped a long time ago.

2021-01-13 03:49 UTC, fkrauthan commented
Created merge request in nucleos/NucleosUserBundle#200 to make `UserFormEvent` extend `FormEvent`. This will require a new release of the user bundle to be compatible.

2021-01-16 22:14 UTC, core23 commented
There is a new 1.7.0 release of the user bundle. Please bump the user-bundle version inside the `composer.json` file.

2021-01-16 22:15 UTC, fkrauthan commented
> There is a new 1.7.0 release of the user bundle. Please bump the user-bundle version inside the `composer.json` file.

Done

2021-01-17 18:34 UTC, core23 commented on src/Event/UserFormEvent.php
> +
```suggestion

```

2021-01-17 18:35 UTC, core23 commented on src/Event/UserFormEvent.php
> +class UserFormEvent extends FormEvent
```suggestion
final class UserFormEvent extends FormEvent
```

2021-01-17 18:39 UTC, merged

2021-01-17 18:39 UTC, core23 commented
Thanks @fkrauthan